version: '2'
services:
  backend-mysql:
    image: mysql:5.7
    # volumes:
    #     - ~/volumes/jhipster/backend/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=Loonaverse
      - MYSQL_ROOT_PASSWORD=Loonaverse
      - MYSQL_PASSWORD=Loonaverse
      - MYSQL_DATABASE=Loonaverse
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp